-- !!!!!!!!!!!!!!!!!!!!!!! WARNING !!!!!!!!!!!!!!!!!!!!!!!
-- This file is automaticly generated. Don't edit manualy!
-- !!!!!!!!!!!!!!!!!!!!!!! WARNING !!!!!!!!!!!!!!!!!!!!!!!

---@alias CalendarCommandType number|"Enum.CalendarCommandType.CalendarCommandCreate"|"Enum.CalendarCommandType.CalendarCommandInvite"|"Enum.CalendarCommandType.CalendarCommandRsvp"|"Enum.CalendarCommandType.CalendarCommandRemoveInvite"|"Enum.CalendarCommandType.CalendarCommandRemoveEvent"|"Enum.CalendarCommandType.CalendarCommandStatus"|"Enum.CalendarCommandType.CalendarCommandModeratorStatus"|"Enum.CalendarCommandType.CalendarCommandGetCalendar"|"Enum.CalendarCommandType.CalendarCommandGetEvent"|"Enum.CalendarCommandType.CalendarCommandUpdateEvent"|"Enum.CalendarCommandType.CalendarCommandComplain"|"Enum.CalendarCommandType.CalendarCommandNotes"

---@alias CalendarErrorType number|"Enum.CalendarErrorType.CalendarErrorSuccess"|"Enum.CalendarErrorType.CalendarErrorCommunityEventsExceeded"|"Enum.CalendarErrorType.CalendarErrorEventsExceeded"|"Enum.CalendarErrorType.CalendarErrorSelfInvitesExceeded"|"Enum.CalendarErrorType.CalendarErrorOtherInvitesExceeded"|"Enum.CalendarErrorType.CalendarErrorNoPermission"|"Enum.CalendarErrorType.CalendarErrorEventInvalid"|"Enum.CalendarErrorType.CalendarErrorNotInvited"|"Enum.CalendarErrorType.CalendarErrorUnknownError"|"Enum.CalendarErrorType.CalendarErrorNotInGuild"|"Enum.CalendarErrorType.CalendarErrorNotInCommunity"|"Enum.CalendarErrorType.CalendarErrorTargetAlreadyInvited"|"Enum.CalendarErrorType.CalendarErrorNameNotFound"|"Enum.CalendarErrorType.CalendarErrorWrongFaction"|"Enum.CalendarErrorType.CalendarErrorIgnored"|"Enum.CalendarErrorType.CalendarErrorInvitesExceeded"|"Enum.CalendarErrorType.CalendarErrorInvalidMaxSize"|"Enum.CalendarErrorType.CalendarErrorInvalidDate"|"Enum.CalendarErrorType.CalendarErrorInvalidTime"|"Enum.CalendarErrorType.CalendarErrorNoInvites"|"Enum.CalendarErrorType.CalendarErrorNeedsTitle"|"Enum.CalendarErrorType.CalendarErrorEventPassed"|"Enum.CalendarErrorType.CalendarErrorEventLocked"|"Enum.CalendarErrorType.CalendarErrorDeleteCreatorFailed"|"Enum.CalendarErrorType.CalendarErrorDataAlreadySet"|"Enum.CalendarErrorType.CalendarErrorCalendarDisabled"|"Enum.CalendarErrorType.CalendarErrorRestrictedAccount"|"Enum.CalendarErrorType.CalendarErrorArenaEventsExceeded"|"Enum.CalendarErrorType.CalendarErrorRestrictedLevel"|"Enum.CalendarErrorType.CalendarErrorSquelched"|"Enum.CalendarErrorType.CalendarErrorNoInvite"|"Enum.CalendarErrorType.CalendarErrorComplaintDisabled"|"Enum.CalendarErrorType.CalendarErrorComplaintSelf"|"Enum.CalendarErrorType.CalendarErrorComplaintSameGuild"|"Enum.CalendarErrorType.CalendarErrorComplaintGm"|"Enum.CalendarErrorType.CalendarErrorComplaintLimit"|"Enum.CalendarErrorType.CalendarErrorComplaintNotFound"|"Enum.CalendarErrorType.CalendarErrorEventWrongServer"|"Enum.CalendarErrorType.CalendarErrorNoCommunityInvites"|"Enum.CalendarErrorType.CalendarErrorInvalidSignup"|"Enum.CalendarErrorType.CalendarErrorNoModerator"|"Enum.CalendarErrorType.CalendarErrorModeratorRestricted"|"Enum.CalendarErrorType.CalendarErrorInvalidNotes"|"Enum.CalendarErrorType.CalendarErrorInvalidTitle"|"Enum.CalendarErrorType.CalendarErrorInvalidDescription"|"Enum.CalendarErrorType.CalendarErrorInvalidClub"|"Enum.CalendarErrorType.CalendarErrorCreatorNotFound"|"Enum.CalendarErrorType.CalendarErrorEventThrottled"|"Enum.CalendarErrorType.CalendarErrorInviteThrottled"|"Enum.CalendarErrorType.CalendarErrorInternal"|"Enum.CalendarErrorType.CalendarErrorComplaintAdded"

---@alias CalendarEventBits number|"Enum.CalendarEventBits.CalendarEventBitPlayer"|"Enum.CalendarEventBits.CalendarEventBitGuildDeprecated"|"Enum.CalendarEventBits.CalendarEventBitSystem"|"Enum.CalendarEventBits.CalendarEventBitHoliday"|"Enum.CalendarEventBits.CalendarEventBitLocked"|"Enum.CalendarEventBits.CalendarEventBitAutoApprove"|"Enum.CalendarEventBits.CalendarEventBitCommunityAnnouncement"|"Enum.CalendarEventBits.CalendarEventBitRaidLockout"|"Enum.CalendarEventBits.CalendarEventBitArenaDeprecated"|"Enum.CalendarEventBits.CalendarEventBitRaidResetDeprecated"|"Enum.CalendarEventBits.CalendarEventBitCommunitySignup"|"Enum.CalendarEventBits.CalendarEventBitGuildSignup"|"Enum.CalendarEventBits.CommunityWide"|"Enum.CalendarEventBits.PlayerCreated"|"Enum.CalendarEventBits.CantComplain"

---@alias CalendarEventRepeatOptions number|"Enum.CalendarEventRepeatOptions.CalendarRepeatNever"|"Enum.CalendarEventRepeatOptions.CalendarRepeatWeekly"|"Enum.CalendarEventRepeatOptions.CalendarRepeatBiweekly"|"Enum.CalendarEventRepeatOptions.CalendarRepeatMonthly"

---@alias CalendarEventType number|"Enum.CalendarEventType.Raid"|"Enum.CalendarEventType.Dungeon"|"Enum.CalendarEventType.PvP"|"Enum.CalendarEventType.Meeting"|"Enum.CalendarEventType.Other"|"Enum.CalendarEventType.HeroicDeprecated"

---@alias CalendarFilterFlags number|"Enum.CalendarFilterFlags.WeeklyHoliday"|"Enum.CalendarFilterFlags.Darkmoon"|"Enum.CalendarFilterFlags.Battleground"|"Enum.CalendarFilterFlags.RaidLockout"|"Enum.CalendarFilterFlags.RaidReset"

---@alias CalendarGetEventType number|"Enum.CalendarGetEventType.Get"|"Enum.CalendarGetEventType.Add"|"Enum.CalendarGetEventType.Copy"|"Enum.CalendarGetEventType.DefaultCalendarGetEventType"

---@alias CalendarHolidayFilterType number|"Enum.CalendarHolidayFilterType.Weekly"|"Enum.CalendarHolidayFilterType.Darkmoon"|"Enum.CalendarHolidayFilterType.Battleground"

---@alias CalendarInviteBits number|"Enum.CalendarInviteBits.CalendarInviteBitPendingInvite"|"Enum.CalendarInviteBits.CalendarInviteBitModerator"|"Enum.CalendarInviteBits.CalendarInviteBitCreator"|"Enum.CalendarInviteBits.CalendarInviteBitSignup"

---@alias CalendarInviteSortType number|"Enum.CalendarInviteSortType.CalendarInviteSortName"|"Enum.CalendarInviteSortType.CalendarInviteSortLevel"|"Enum.CalendarInviteSortType.CalendarInviteSortClass"|"Enum.CalendarInviteSortType.CalendarInviteSortStatus"|"Enum.CalendarInviteSortType.CalendarInviteSortParty"|"Enum.CalendarInviteSortType.CalendarInviteSortNotes"

---@alias CalendarInviteType number|"Enum.CalendarInviteType.Normal"|"Enum.CalendarInviteType.Signup"

---@alias CalendarModeratorStatus number|"Enum.CalendarModeratorStatus.CalendarModeratorNone"|"Enum.CalendarModeratorStatus.CalendarModeratorModerator"|"Enum.CalendarModeratorStatus.CalendarModeratorCreator"

---@alias CalendarStatus number|"Enum.CalendarStatus.Invited"|"Enum.CalendarStatus.Available"|"Enum.CalendarStatus.Declined"|"Enum.CalendarStatus.Confirmed"|"Enum.CalendarStatus.Out"|"Enum.CalendarStatus.Standby"|"Enum.CalendarStatus.Signedup"|"Enum.CalendarStatus.NotSignedup"|"Enum.CalendarStatus.Tentative"

---@alias CalendarType number|"Enum.CalendarType.Player"|"Enum.CalendarType.Community"|"Enum.CalendarType.RaidLockout"|"Enum.CalendarType.RaidResetDeprecated"|"Enum.CalendarType.Holiday"|"Enum.CalendarType.HolidayWeekly"|"Enum.CalendarType.HolidayDarkmoon"|"Enum.CalendarType.HolidayBattleground"

---@alias CalendarWebActionType number|"Enum.CalendarWebActionType.Accept"|"Enum.CalendarWebActionType.Decline"|"Enum.CalendarWebActionType.Remove"|"Enum.CalendarWebActionType.ReportSpam"|"Enum.CalendarWebActionType.Signup"|"Enum.CalendarWebActionType.Tentative"|"Enum.CalendarWebActionType.TentativeSignup"

---@alias HolidayCalendarFlags number|"Enum.HolidayCalendarFlags.Alliance"|"Enum.HolidayCalendarFlags.Horde"

---@alias HolidayFlags number|"Enum.HolidayFlags.IsRegionwide"|"Enum.HolidayFlags.DontShowInCalendar"|"Enum.HolidayFlags.DontDisplayEnd"|"Enum.HolidayFlags.DontDisplayBanner"|"Enum.HolidayFlags.NotAvailableClientSide"

